In [64]:
import numpy as np
from numba import njit

In [33]:
ny = 10
y = np.arange(ny)
v_init = 5*(1 + 1e-4*np.sin(2*np.pi/(ny-1)*y))
zeros = np.zeros(ny)
u = np.array([np.column_stack((v_init, zeros)) for _ in range(5)])

In [34]:
u.shape

(5, 10, 2)

In [35]:
np.linalg.norm(u, axis=2).shape

(5, 10)

In [40]:
v = np.array([-1,-1])

In [42]:
u@v

array([[-5.        , -5.00032139, -5.0004924 , -5.00043301, -5.00017101,
        -4.99982899, -4.99956699, -4.9995076 , -4.99967861, -5.        ],
       [-5.        , -5.00032139, -5.0004924 , -5.00043301, -5.00017101,
        -4.99982899, -4.99956699, -4.9995076 , -4.99967861, -5.        ],
       [-5.        , -5.00032139, -5.0004924 , -5.00043301, -5.00017101,
        -4.99982899, -4.99956699, -4.9995076 , -4.99967861, -5.        ],
       [-5.        , -5.00032139, -5.0004924 , -5.00043301, -5.00017101,
        -4.99982899, -4.99956699, -4.9995076 , -4.99967861, -5.        ],
       [-5.        , -5.00032139, -5.0004924 , -5.00043301, -5.00017101,
        -4.99982899, -4.99956699, -4.9995076 , -4.99967861, -5.        ]])

In [44]:
(v[0]*u[:,:,0] + v[1]*u[:,:,1]) == u@v

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [48]:
row = np.array([
    [0,1,2,3,4,5,6,7,8],
    [0,1,2,3,4,5,6,7,8],
    [0,1,2,3,4,5,6,7,8],
    [0,1,2,3,4,5,6,7,8]
])

In [49]:
for i in range(3):
    row[:,8-i] = row[:,i]

In [50]:
row

array([[0, 1, 2, 3, 4, 5, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 2, 1, 0]])

In [66]:
class A:
    
    def __init__(self):
        self.row = np.array([
            [0,1,2,3,4,5,6,7,8],
            [0,1,2,3,4,5,6,7,8],
            [0,1,2,3,4,5,6,7,8],
            [0,1,2,3,4,5,6,7,8]
            ])
    

    @staticmethod
    @njit
    def func(row):
        for i in range(3):
            row[:,8-i] = row[:,i]
            
    def change(self):
        self.func(self.row)

In [71]:
obj = A()

In [72]:
obj.row

array([[0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [73]:
obj.change()

In [74]:
obj.row

array([[0, 1, 2, 3, 4, 5, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 2, 1, 0],
       [0, 1, 2, 3, 4, 5, 2, 1, 0]])

In [75]:
a = np.array([
    np.ones((5,5)),
    np.ones((5,5)),
    np.ones((5,5)),
])

In [77]:
np.sum(a, axis=0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [78]:
v = np.array([[1, 1], [1, 0], [1, -1], [0, 1], 
                      [0, 0], 
                      [0, -1], [-1, 1], [-1, 0], [-1, -1]])

In [115]:
f_in = np.ones((9, 10, 10))

In [94]:
np.multiply(f_in, v, out=(9, 10, 10, 2))

ValueError: The 'out' tuple must have exactly one entry per ufunc output

In [88]:
f_in [:, 0, 0]

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
(*f_in.shape, 2)

(9, 10, 10, 2)

In [117]:
f = f_in[:,:,:,np.newaxis]
f.shape

(9, 10, 10, 1)

In [111]:
f

(9, 10, 10, 1)

In [118]:
m = np.ones((9,10, 10, 2))

In [121]:
np.sum(m, axis=0).shape

(10, 10, 2)

In [124]:
y = np.arange(10)
v_init = 5*(1 + 1e-4*np.sin(2*np.pi/(10-1)*y))
zeros = np.zeros(10)
u = np.array([np.column_stack((v_init, zeros)) for _ in range(10)])

In [137]:
index = np.array([[4,5], [7, 8], [9,0]])
f_in[0][[0,]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [143]:
test = np.diag((1, 2, 3, 4, 5, 6, 7))

In [144]:
test

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [147]:
np.roll(np.roll(test, 1, axis=1), -1, axis=0)

array([[0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [7, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0]])